### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Teloc-Arioch** [brangerjoe/mage-spellbook#1]
Data has no rotes under it even if you select 5th level.  
![image](https://github.com/brangerjoe/mage-spellbook/assets/148037127/169f4cb1-bdca-4fbc-b184-b7f748c106b7)

**Comment by brangerjoe** [comment]
This was intended as there were no Data-only rotes in the book. However, https://github.com/brangerjoe/mage-spellbook/commit/09c5952b97b29110f2d553de7b6c463ae197aa1f will also fix it as it merges Data into Correspondence.
