### ISSUE TITLE
"Or" logic wrong when reading spheres

### ISSUE THREAD

**Issue by Teloc-Arioch** [brangerjoe/mage-spellbook#6]
The "or" logic when reading spheres causes the following: 

"Prime 2, Cor 2, Time 2 or Entropy 2" was becoming 

"Prime 2, Cor 2, Time 2"  or  "Entropy 2"

When it should become: 

"Prime 2, Cor 2, Time 2" or
"Prime 2, Cor 2, Entropy 2"

cs

**Comment by brangerjoe** [comment]
Fixed to address this.
